name: Publish to gh-pages

on:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn
    - run: yarn run build
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: release/v0-01
        build_dir: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}